### ISSUE TITLE
Inquiry about some metrics

### ISSUE THREAD

**Issue by guanjunwu** [GANWANSHUI/V4D#5]
Hi, thanks for your great work!
I want to add comparasion in my paper with my methods, but I have no time to run the code. Could you tell me:
1. Average disk costs on D-NeRF datasets.
2. training time, FPS, disk costs on hypernerf vrig datasets.
Looking forward to your apply!

**Comment by GANWANSHUI** [comment]
@guanjunwu Thanks a lot for the comparison. 

1. Average disk costs on D-NeRF datasets. (377MB)

2. training time (5.5 hours,), FPS (3.4 seconds per frame), disk costs (377MB) on hypernerf vrig datasets.

The reason for the much longer inference time in the  hypernerf vrig datasets is that we did not use the strategy to fine bounding box.
